"""create user model

Revision ID: 13fd9bb4da65
Revises: 2d95db27a8aa
Create Date: 2025-06-09 21:55:20.321089

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '13fd9bb4da65'
down_revision = '2d95db27a8aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=mysql.ENUM('BOAED', 'POST', 'COMMENT', 'FRONT_USER', 'CMS_USER'),
               type_=sa.Enum('BOARD', 'POST', 'COMMENT', 'FRONT_USER', 'CMS_USER', name='permissionenum'),
               existing_nullable=False)

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('_password', sa.String(length=200), nullable=False))
        batch_op.drop_column('password')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('password', mysql.VARCHAR(length=200), nullable=False))
        batch_op.drop_column('_password')

    with op.batch_alter_table('permission', schema=None) as batch_op:
        batch_op.alter_column('name',
               existing_type=sa.Enum('BOARD', 'POST', 'COMMENT', 'FRONT_USER', 'CMS_USER', name='permissionenum'),
               type_=mysql.ENUM('BOAED', 'POST', 'COMMENT', 'FRONT_USER', 'CMS_USER'),
               existing_nullable=False)

    # ### end Alembic commands ###
